config/routes.rb
Wantatoy::Application.routes.draw do

  match 'toys/thanks' => 'toys#message', :as => :thanks

  match 'toys/activation/:token' => 'toys#activation', :as => :activation
  
  match 'toys/cancel/:token' => 'toys#cancelation', :as => :cancelation
  
  match 'location' => 'location#edit', :as => :edit_location

  resources :toys do
    resources :contacts
  end
  

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t 'title'%></title>
	<%= stylesheet_link_tag("jquery-ui-1.8.12.custom")%>
    <%= stylesheet_link_tag("reset")%>
    <%= stylesheet_link_tag("text")%>
    <%= stylesheet_link_tag("960")%>
	<%= stylesheet_link_tag("styles")%>
	<%= javascript_include_tag :defaults %>

  </head>
<body>
<div id="container">		
	<div id="header">
		<div class="container_16">
		<div class="grid_4"><h1>Juguetea</h1></div>
		<div class="grid_12">
			<nav>
			<ul id="nav">				  
				<li><%= link_to t('menu.home'), {:controller => 'home'},
						{:class => "#{if (params[:controller] == 'home') then 'current' end}"}%>
				</li>
				<li>
					<%= link_to t('menu.toys'), toys_path, 
						{:class => "#{if ((params[:controller] == 'toys' and params[:action] != 'new' and params[:action] != 'create' and params[:action] != 'thanks') || params[:controller] == 'contacts') then 'current' end}"} %>
				</li>				
				<li>
					<%= link_to t('menu.new_toy'), new_toy_path, 
						{:class => "#{if (params[:controller] == 'toys' and (params[:action] == 'new' or params[:action] == 'create')) then 'current' end}"} %>
				</li>
			</ul>
			</nav>
		</div>
		<div class="clear"></div>
		</div>	
	</div>
	<div id="currentlocation">	
		<div class="container_16">
			<div class="grid_16">
				<h6><%= t 'location', :location => "#{Location.new(session[:geo_location].city, session[:geo_location].state, 'ES').to_s}" %> 
					<%= link_to 'Cambiar', :edit_location %></h6>
				</div>
			<div class="clear"></div>
		</div>
	</div>
	<div id="content">
	<%= yield %>
	</div>	
	<div id="footer">
		<div class="container_16">
			<div class="grid_15"><p><%= t 'footer.message'%></p></div>
			<div class="grid_1">
				<div id="twitter"><a href="http://www.twitter.com/juguetea_org" target="_blank"><%= image_tag "twitter-icon.png"%></a></div>
			</div>		
			<div class="clear"></div>
		</div>
	</div>	
</div>
</body>
</html>
<%= javascript_include_tag 'jquery.limit-1.2' %>